version: '3.8'

services:
  minecraft-server:
    build: .
    container_name: mc-server
    environment:
      EULA: "TRUE"
      VERSION: "latest"
      MAX_PLAYERS: 20
    ports:
      - "25565:25565"
    volumes:
      - mcdata:/minecraft/data
    restart: always

volumes:
  mcdata:
